### PR TITLE
add support for macOS `say` text to speech command

### PR DESCRIPTION
**Pull request by zimmermatt**

### CODE REVIEW

**Comment by luc-vocab** [comment]
mp3 format seems more fitting for Anki, any reason why you picked aiff ? the "say" command will infer the type from the file extension

**Comment by zimmermatt** [comment]
> mp3 format seems more fitting for Anki, any reason why you picked aiff ? the "say" command will infer the type from the file extension

Good point and question. I had hoped to be able to generate `mp3` directly, But, when I tested generating audio in`mp3` format by manually running `say -o test.mp3 "test text"`. Opening the resulting output file yielded an error (other formats like `flac` and `ogg` work, however). Given that, the historical license encumbrance with `mp3`, and that _AwesomeTTS_ generated `aiff` and transcoded to `mp3`, I figured this path had been unsuccessfully attempted before. So, I didn't pursue it any further. I didn't follow the `mp3` transcoding step used in _AwesomeTTS_, figuring we could discuss whether that was still desired or if we wanted to use one of the other supported formats through PR discussion. Or, that you would want go ahead and add it, so I enabled "Allow edits from maintainers."

**Comment by zimmermatt** [comment]
Huh... `mp3` is no longer encumbered (since 2017).

https://www.iis.fraunhofer.de/en/ff/amm/consumer-electronics/mp3.html

**Comment by luc-vocab** [comment]
I changed it to default to mp3. We can add support for other formats if required. HyperTTS supports ogg and ogg opus with some services. For collection audio, we would need to make sure the mobile apps support the various formats.

**Pull request merged**
